added support for changes.xml

diff --git a/bin/releasator b/bin/releasator
--- a/bin/releasator
+++ b/bin/releasator
@@ -18,10 +18,6 @@
 #
 function prepare() {
 	VERSION=${1?'Please specify version as the first argument'}
-	if [ -f "changes.xml" ]; then
-		echo "ERROR: Implementation handling changes.xml is missing" >&2
-		return 1
-	fi
 	ORIG_BUILDNUMBER=$(xmllint --xpath '/*/*[name()="properties"]/*[name()="buildNumber"]/text()' pom.xml)
 	NAME=$(xmllint --xpath '/*/*[name()="artifactId"]/text()' pom.xml)
 	TAGNAME="$NAME-$VERSION"
@@ -33,18 +29,34 @@ function prepare() {
 	SCM_DC=$(xmllint --xpath '/*/*[name()="scm"]/*[name()="developerConnection"]/text()' pom.xml)
 	if [ -z "$SCM_DC" ]; then
 		echo "ERROR: Missing tag /project/scm/developerConnection" >&2
-		exit 1
+#		exit 1
 	fi
 	local existingTags=$(git tag -l "$TAGNAME")
 	case "$existingTags" in
 	'');;
 	*) echo "ERROR: Tag '$TAGNAME' already exists: $existingTags" >&2; return 1;;
 	esac
+	if [ -f "changes.xml" ]; then
+		local releaseLine='<release version="'$DEVEL_VERSION'" '
+		echo "R=*$releaseLine*"
+		local releaseLineCnt=$(grep "${releaseLine}" changes.xml | wc -l)
+		if [ "$releaseLineCnt" != "1" ]; then
+			echo "ERROR: changes.xml: expected one release line ($releaseLine) but found $releaseLineCnt" >&2
+			return 1
+		fi
+		local TODAY=$(date '+%F')
+		sed 's:'"$releaseLine"':<release version="'$VERSION'" date="'"$TODAY"'" :' changes.xml >release-changes.xml
+		mv "release-changes.xml" "changes.xml"
+
+		sed 's:<body>:<body>\n        <release version="'"$DEVEL_VERSION"'">\n        <!-- add changes here -->\n        </release>:' changes.xml >.git/next-changes.xml
+#		echo "ERROR: Implementation handling changes.xml is missing" >&2; return 1
+	fi
 	if [ -n "$ORIG_BUILDNUMBER" ]; then
 		CODENAME=${2?'This project uses buildNumber property. Please specify codename as the second argument to be used for buildNumber'}
 		sed -i 's:<\(buildNumber>\).*</buildNumber>:<\1'"$CODENAME"'</\1:' pom.xml || return 1
-		git commit -am "Releasing $NAME-$VERSION: changed buildNumber to '$CODENAME'" || return 1
+#		git commit -am "Releasing $NAME-$VERSION: changed buildNumber to '$CODENAME'" || return 1
 	fi
+	git commit -am "[releasator] Pre-release changes for $NAME-$VERSION" || return 1
 	RELEASE_DIR=$HOME/.m2/releases/$NAME-$VERSION
 
 	echo "Releasing project '$NAME' in version '$DEVEL_VERSION' as version '$VERSION' from $SCM_DC"
@@ -61,8 +73,14 @@ function prepare() {
 	-DpreparationGoals="clean deploy" \
 	-DpushChanges=false || return 1
 
+	if [ -f "changes.xml" ]; then
+		echo "Preparing changes.xml for further development"
+		mv ".git/next-changes.xml" "changes.xml" || return 1
+		git commit --amend changes.xml --no-edit || return 1
+	fi
 
 	if [ -n "$ORIG_BUILDNUMBER" ]; then
+		echo "returning original buildNumber value"
 		# silently change the buildNumber back - no special commit
 		sed -i 's:<\(buildNumber>\).*</buildNumber>:<\1'"$ORIG_BUILDNUMBER"'</\1:' pom.xml || return 1
 		git commit --amend pom.xml --no-edit || return 1
